name: Publish to DockerHub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN  }}

    - name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Extract branch name (fallback for workflow_dispatch)
      if: !startsWith(github.ref, 'refs/tags/')
      run: echo "TAG_NAME=latest" >> $GITHUB_ENV

    - name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ env.TAG_NAME }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

    - name: Generate artifact
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true